{
 "title": "Pizza",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizzas Being Sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sales_sectionPizza{source=\"jwt-pizza-service-dev\"} * 6",
     "legendFormat": "Pizzas per minute"
    },
    {
     "expr": "avg_over_time(sales_sectionPizza{source=\"jwt-pizza-service-dev\"}[$__interval]) * 6",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "System Monitor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_cpuPercentage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_memoryPercentage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Total Pizzas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sales_totalPizza{source=\"jwt-pizza-service-dev\"}[$__interval])",
     "legendFormat": "Total Pizzas Sold"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(auth_successful{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_failure{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_currentCount{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CurentUsers"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(requests_totalHttp{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(requests_getHttp{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(requests_postHttp{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(requests_putHttp{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(requests_deleteHttp{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "latency_service{source=\"jwt-pizza-service-dev\"} < 5000",
     "legendFormat": "Backend"
    },
    {
     "expr": "avg(latency_pizzaFactory{source=\"jwt-pizza-service-dev\"})",
     "legendFormat": "Requests to Pizza Factory"
    }
   ]
  },
  {
   "title": "$ Money $ ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sales_moneyEarned{source=\"jwt-pizza-service-dev\"}[$__interval])",
     "legendFormat": "Money Made"
    }
   ]
  }
 ]
}